# Generated by Django 3.2.20 on 2023-07-18 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('totalStudents', models.IntegerField(default=0)),
                ('totalClasses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('enrolmentId', models.AutoField(primary_key=True, serialize=False)),
                ('classesAttended', models.IntegerField(default=0)),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app0.course')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app0.student')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('time', models.DateTimeField(auto_created=True)),
                ('attendanceId', models.AutoField(primary_key=True, serialize=False)),
                ('presentStudents', models.IntegerField(default=0)),
                ('attendedStudents', models.ManyToManyField(to='app0.Student')),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app0.course')),
            ],
        ),
    ]
