# Generated by Django 3.2.20 on 2023-07-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancelog',
            old_name='courseId',
            new_name='courseObj',
        ),
        migrations.RenameField(
            model_name='enrolment',
            old_name='courseId',
            new_name='courseObj',
        ),
        migrations.RenameField(
            model_name='enrolment',
            old_name='studentId',
            new_name='studentObj',
        ),
    ]
