# Generated by Django 3.2.20 on 2023-07-18 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app0', '0002_auto_20230718_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancelog',
            old_name='attendanceId',
            new_name='attendanceLogId',
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceId', models.CharField(max_length=50)),
                ('attendanceLogObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app0.attendancelog')),
                ('studentObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app0.student')),
            ],
        ),
    ]
