# Generated by Django 3.2.20 on 2023-07-19 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0004_auto_20230719_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacherObj',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app0.teacher'),
            preserve_default=False,
        ),
    ]
